feat: Added interface for swagger options
nestjs/swagger pull request #1693
Opened 2021-11-24 02:27 UTC by seebeen

Options object defined from this page: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe: 

## What is the current behavior?
Currently, Swagger Options have no interface object, meaning that anyone that wants to customize swagger needs to google the options, and read stackoverflow answers in order to learn how to customize
Issue Number: N/A

## What is the new behavior?
I've added a documented interface from swagger docs with some commonly used options

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2021-11-24 13:54 UTC, micalevisk commented on lib/interfaces/swagger-custom-options.interface.ts
> +export interface SwaggerConfigurationOptions {
```suggestion
/**
 * Check out all available `swagger-ui` options here:
 * {@link https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md}
 */
export interface SwaggerConfigurationOptions {
```

2021-11-24 13:56 UTC, micalevisk requested changes
well done!

can you do `npm run format` (and commit just `swagger-custom-options.interface.ts`)

2021-11-24 17:49 UTC, jmcdo29 commented
Are all of these options available for `swagger-ui-express` and `fastify-swagger`?

2021-11-24 19:09 UTC, seebeen commented
> Are all of these options available for `swagger-ui-express` and `fastify-swagger`?

As far as I'm aware these are native swagger options you can use for both express / fastify because they're mostly used for handling the UI side of things.

I've tested some of the options (persistAuth, docExpansion) on fastify. Works as expected.

2021-11-24 19:12 UTC, seebeen commented
> well done!
> 
> can you do `npm run format` (and commit just `swagger-custom-options.interface.ts`)

Done :)

2021-11-25 11:16 UTC, seebeen commented
@jmcdo29 All good? Can the PR be merged? :)

2022-07-08 08:07 UTC, kamilmysliwiec commented
This PR does not seem to be relevant anymore after merging this PR https://github.com/nestjs/swagger/pull/1886

2022-07-08 08:07 UTC, closed without merging